spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:sk-1234}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 0.1
          max-tokens: 1000
          #model: gpt-4.1-mini
          # gpt 5 이상에서는 temperature가 1.0이여야만 동작가능